-- Migration: Add EXIF metadata columns to media table
ALTER TABLE media ADD COLUMN IF NOT EXISTS exif_make VARCHAR;
ALTER TABLE media ADD COLUMN IF NOT EXISTS exif_model VARCHAR;
ALTER TABLE media ADD COLUMN IF NOT EXISTS exif_date_taken TIMESTAMP;
ALTER TABLE media ADD COLUMN IF NOT EXISTS exif_latitude DOUBLE PRECISION;
ALTER TABLE media ADD COLUMN IF NOT EXISTS exif_longitude DOUBLE PRECISION;
ALTER TABLE media ADD COLUMN IF NOT EXISTS exif_width INTEGER;
ALTER TABLE media ADD COLUMN IF NOT EXISTS exif_height INTEGER;
ALTER TABLE media ADD COLUMN IF NOT EXISTS exif_iso INTEGER;
ALTER TABLE media ADD COLUMN IF NOT EXISTS exif_aperture DOUBLE PRECISION;
ALTER TABLE media ADD COLUMN IF NOT EXISTS exif_shutter_speed VARCHAR;
ALTER TABLE media ADD COLUMN IF NOT EXISTS exif_focal_length DOUBLE PRECISION;
